name: GambleLife
version: '${project.version}'
main: org.gamblelife.gamble.GambleLife
api-version: '1.20'
commands:
  택시:
    description: 택시 메뉴를 엽니다.
    usage: /택시 <playername>
  giveRegenerationWind:
    description: 재생의 바람 아이템을 지급합니다.
    usage: /<command>
    permission: gamblelife.givewind
  환전:
    description: 원하는 액면가의 게임 칩으로 환전합니다.
    usage: /환전 <액면가> <갯수(기본값1)>
    aliases: [exchange]
permissions:
  gamblelife.givewind:
    description: 재생의 바람 아이템을 받을 수 있는 권한
    default: op
